version: '3.9'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      MYSQL_CHARACTER_SET_SERVER: ${MYSQL_CHARACTER_SET_SERVER}
      MYSQL_COLLATION_SERVER: ${MYSQL_COLLATION_SERVER}
      MYSQL_INITDB_SKIP_TZINFO: ${MYSQL_INITDB_SKIP_TZINFO}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080